INFO 2024-08-11 13:28:49,515 autoreload Watching for file changes with StatReloader
INFO 2024-08-11 13:29:31,985 autoreload Watching for file changes with StatReloader
WARNING 2024-08-11 13:30:20,587 log Not Found: /books
WARNING 2024-08-11 13:30:20,617 basehttp "GET /books HTTP/1.1" 404 2607
INFO 2024-08-11 13:30:29,805 basehttp "GET /admin/ HTTP/1.1" 302 0
ERROR 2024-08-11 13:30:31,018 log Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\utils\module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\utils\module_loading.py", line 16, in cached_import
    return getattr(module, class_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'base_api.authentication' has no attribute 'CustomerAuthentication'. Did you mean: 'CustomerAuthenticationBackend'?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\contrib\admin\sites.py", line 425, in login
    **self.each_context(request),
      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\contrib\admin\sites.py", line 338, in each_context
    "available_apps": self.get_app_list(request),
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\contrib\admin\sites.py", line 541, in get_app_list
    app_dict = self._build_app_dict(request, app_label)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\contrib\admin\sites.py", line 483, in _build_app_dict
    has_module_perms = model_admin.has_module_permission(request)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\contrib\admin\options.py", line 640, in has_module_permission
    return request.user.has_module_perms(self.opts.app_label)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\contrib\auth\models.py", line 489, in has_module_perms
    return _user_has_module_perms(self, module)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\contrib\auth\models.py", line 232, in _user_has_module_perms
    for backend in auth.get_backends():
                   ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 40, in get_backends
    return _get_backends(return_tuples=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 29, in _get_backends
    backend = load_backend(backend_path)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 23, in load_backend
    return import_string(path)()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\utils\module_loading.py", line 32, in import_string
    raise ImportError(
ImportError: Module "base_api.authentication" does not define a "CustomerAuthentication" attribute/class
ERROR 2024-08-11 13:30:31,159 basehttp "GET /admin/login/?next=/admin/ HTTP/1.1" 500 135643
WARNING 2024-08-11 13:30:36,490 log Not Found: /api/tasks/
WARNING 2024-08-11 13:30:36,496 basehttp "GET /api/tasks/ HTTP/1.1" 404 9987
INFO 2024-08-11 13:30:40,611 basehttp "GET /api/books HTTP/1.1" 301 0
WARNING 2024-08-11 13:30:40,791 log Forbidden: /api/books/
WARNING 2024-08-11 13:30:40,794 basehttp "GET /api/books/ HTTP/1.1" 403 5022
INFO 2024-08-11 13:30:41,211 basehttp "GET /static/rest_framework/js/load-ajax-form.js HTTP/1.1" 200 59
INFO 2024-08-11 13:30:41,379 basehttp "GET /static/rest_framework/js/jquery-3.7.1.min.js HTTP/1.1" 200 87533
INFO 2024-08-11 13:32:05,137 autoreload C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\bookstore\settings.py changed, reloading.
INFO 2024-08-11 13:32:07,329 autoreload Watching for file changes with StatReloader
INFO 2024-08-11 13:32:10,195 basehttp "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4157
ERROR 2024-08-11 13:32:18,520 log Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\contrib\admin\sites.py", line 444, in login
    return LoginView.as_view(**defaults)(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\views\decorators\debug.py", line 143, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\contrib\auth\views.py", line 89, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\views\generic\edit.py", line 150, in post
    if form.is_valid():
       ^^^^^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\forms\forms.py", line 197, in is_valid
    return self.is_bound and not self.errors
                                 ^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\forms\forms.py", line 192, in errors
    self.full_clean()
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\forms\forms.py", line 326, in full_clean
    self._clean_form()
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\forms\forms.py", line 342, in _clean_form
    cleaned_data = self.clean()
                   ^^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\contrib\auth\forms.py", line 329, in clean
    self.user_cache = authenticate(
                      ^^^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\views\decorators\debug.py", line 75, in sensitive_variables_wrapper
    return func(*func_args, **func_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 79, in authenticate
    user = backend.authenticate(request, **credentials)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\base_api\authentication.py", line 22, in authenticate
    user = Author.objects.get(username=username)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\db\models\query.py", line 635, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\db\models\sql\query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\db\models\sql\query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\db\models\sql\query.py", line 1491, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\db\models\sql\query.py", line 1303, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\db\models\sql\query.py", line 1768, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'username' into field. Choices are: book, customer_ptr, customer_ptr_id, email, groups, id, is_active, is_staff, is_superuser, last_login, logentry, name, order, password, user_permissions
ERROR 2024-08-11 13:32:18,566 basehttp "POST /admin/login/?next=/admin/ HTTP/1.1" 500 231382
INFO 2024-08-11 13:32:47,684 autoreload C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\base_api\urls.py changed, reloading.
INFO 2024-08-11 13:32:49,929 autoreload Watching for file changes with StatReloader
INFO 2024-08-11 13:33:28,942 autoreload C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\base_api\models.py changed, reloading.
INFO 2024-08-11 13:33:30,527 autoreload Watching for file changes with StatReloader
INFO 2024-08-11 13:33:34,272 basehttp "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4157
ERROR 2024-08-11 13:33:41,836 log Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: base_api_customer.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\contrib\admin\sites.py", line 444, in login
    return LoginView.as_view(**defaults)(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\views\decorators\debug.py", line 143, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\contrib\auth\views.py", line 89, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\views\generic\edit.py", line 150, in post
    if form.is_valid():
       ^^^^^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\forms\forms.py", line 197, in is_valid
    return self.is_bound and not self.errors
                                 ^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\forms\forms.py", line 192, in errors
    self.full_clean()
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\forms\forms.py", line 326, in full_clean
    self._clean_form()
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\forms\forms.py", line 342, in _clean_form
    cleaned_data = self.clean()
                   ^^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\contrib\auth\forms.py", line 329, in clean
    self.user_cache = authenticate(
                      ^^^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\views\decorators\debug.py", line 75, in sensitive_variables_wrapper
    return func(*func_args, **func_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 79, in authenticate
    user = backend.authenticate(request, **credentials)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\base_api\authentication.py", line 7, in authenticate
    user = Customer.objects.get(email=email)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\db\models\query.py", line 645, in get
    num = len(clone)
          ^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: base_api_customer.username
ERROR 2024-08-11 13:33:41,892 basehttp "POST /admin/login/?next=/admin/ HTTP/1.1" 500 252695
INFO 2024-08-11 13:34:28,074 autoreload C:\Users\SAMSUNG\Desktop\NAT_HABIT\bookstore\bookstore\settings.py changed, reloading.
